…

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -17,7 +17,7 @@ env:
       if [ "$1" = "$2" ]; then
         printf 'ok: "%s" == "%s"\n' "$1" "$2" >&2
       else
-        printf 'assertion error: "%s" != "%s"\n' "$1" "$2" >&2
+        printf 'assertion error: "%s" != "%s"\n' "$1" "$2" >&2 | tee >(od --width=1000 --address-radix=n --format=c >&2)
         return 1
       fi
     }
